name: Build CI

on:
  pull_request:
  push:
    branches:
      - dev
      - cuckoo
      - language

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VITE_APP_REGISTER_APIKEY: ${{ secrets.REGISTER_APIKEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Build UI version info
        working-directory: ui
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --tags
          REV=`git rev-parse HEAD | rev | cut -c 1-6 | rev`
          TAG=`git tag --sort=creatordate | tail -1`
          echo "VITE_APP_BUILD=..$REV" >> .env
          echo "VITE_APP_VERSION=$TAG" >> .env
          cat .env

      - name: Build UI
        working-directory: ui
        run: |
          rm -rf node_modules package-lock.json
          npm install
          npm run build

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1.0.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install intelhex

      - name: PlatformIO Run 1/2
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: "gravity-8266,gravity-32c3_mini,gravity-32s3_mini,gravity-32s2_mini,gravity-32c3_zero,gravity-32s3_zero"
          jobs: 1
          silent: false
          verbose: true
          disable-auto-clean: false

      - name: PlatformIO Run 2/2
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: "gravity-32c3_supermini,gravity-32c3_cuckoo,gravity-32c3_cuckoo_v2,gravity-olimex_esp32c3_devkit_lipo"
          jobs: 1
          silent: false
          verbose: true
          disable-auto-clean: false

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'bin html'
          author_name: GitHub Action
          author_email: mp-se@noreply.github.com
          default_author: github_actor
          message: 'GitHub Action Build'
          pathspec_error_handling: ignore
